name: rpi-hardware-monitor-ros
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  # - ros-rolling-desktop
  - pip
  - cmake
  - ninja
  - colcon-core
  - colcon-common-extensions
  - numpy
  - pip:
      - catkin_pkg
      - empy>=3.1.0,<4.0.0
      - typing-extensions
      - lark-parser
      - lark
      - pydantic
      - pydantic-core
      - idna>=2.8
      - pre-commit
      - black
      - isort
      - flake8
      - ruff
      - mypy
      - psutil
