name: rpi-hardware-monitor-ros
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - cmake
  - ninja
  - colcon-common-extensions
  - pip:
      - catkin_pkg
      - empy>=3.1.0,<4.0.0
      - typing-extensions
      - lark-parser
      - pydantic
      - pydantic-core
      - idna>=2.8
