name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: scripts/conda-env.yml
          activate-environment: rpi-hardware-monitor-ros
      - name: Lint with pre-commit
        shell: bash -l {0}
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate rpi-hardware-monitor-ros
          pre-commit install --install-hooks
          pre-commit run --all-files --show-diff-on-failure
